name: Build SAT Linux, Mac OS, Windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]  # Добавлены архитектуры для кросс-платформенной совместимости

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'

      - name: Install dependencies
        run: npm install

      - name: Package Steam Auth Tool app
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Универсальная сборка для macOS
            npm run package -- --platform=darwin --arch=universal
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Сборка для Linux
            npm run package -- --platform=linux --arch=${{ matrix.arch }}
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Сборка для Windows
            npm run package -- --platform=win32 --arch=${{ matrix.arch }}
          fi
        env:
          CI: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: out
