name: Build SAT Linux, Mac OS, Windows

# Триггер, который позволяет вручную запускать процесс через интерфейс GitHub
on:
  workflow_dispatch:  # позволяет запускать сборку по команде

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x32, x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'

      - name: Install dependencies
        run: npm install

      - name: Package Steam Auth Tool app
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # macOS: Универсальная сборка (x64 + arm64)
            npm run package -- --arch=universal
          else
            # Linux и Windows: Сборки для x64 и arm64
            npm run package -- --arch=${{ matrix.arch }}
          fi
        env:
          CI: true

      - name: Rename and organize output files
        run: |
          mkdir -p out/release
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv out/Steam Auth Tool-darwin-${{ matrix.arch }} out/release/Steam_Auth_Tool_mac_${{ matrix.arch }}
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            mv out/Steam Auth Tool-linux-${{ matrix.arch }} out/release/Steam_Auth_Tool_linux_${{ matrix.arch }}
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv out/Steam Auth Tool-win32-${{ matrix.arch }} out/release/Steam_Auth_Tool_win_${{ matrix.arch }}
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: out
